# Cleaning Data

## 1. Data Types

In [1]:
import pandas as pd

run_times = pd.read_excel('../Data/Run Times.xlsx')
run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [2]:
# CHECK THE DATA TYPES
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                     object
dtype: object

In [3]:
# CAN ALSO USE .info()
run_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      object
 4   Run Date      5 non-null      datetime64[ns]
 5   Race Date     5 non-null      datetime64[ns]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      object
dtypes: bool(1), datetime64[ns](2), float64(1), object(4)
memory usage: 413.0+ bytes

#### Converting Data Types

In [4]:
run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [5]:
# CHANGE FEE FROM OBJECT TO NUMERIC
run_times.Fee = pd.to_numeric(run_times.Fee.str.replace('$', ''))

In [6]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time            object
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

In [7]:
# CHANGE Warm Up Time FROM OBJECT TO NUMERIC
pd.to_numeric(run_times['Warm Up Time'], errors='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [8]:
# REMOVE THE " min" FROM THE Warm Up Time
run_times['Warm Up Time'].str.replace(' min', '')

0    NaN
1    NaN
2      3
3    NaN
4    NaN
Name: Warm Up Time, dtype: object

In [9]:
# Don't want all those NaN values, cast column to type string first
run_times['Warm Up Time'] = pd.to_numeric(run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [10]:
run_times.dtypes

Name                    object
Run Time               float64
Warm Up Time           float64
Location                object
Run Date        datetime64[ns]
Race Date       datetime64[ns]
Rain                      bool
Fee                    float64
dtype: object

## 2. Missing Data

In [11]:
df = pd.read_excel('../Data/Student Grades.xlsx')
df.tail()

    Student Class    Year  Grade
81      NaN   NaN     NaN    NaN
82  Bennett   NaN     NaN    NaN
83      NaN   EDA  Junior   84.0
84    Gavin   EDA  Senior    NaN
85   Calvin   NaN     NaN  100.0

### a. Find missing data

In [12]:
import numpy as np

# Missing data representations in Python
# np.NaN
# pd.NA
# None

In [13]:
# Quickly explore the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     object
 1   Class    83 non-null     object
 2   Year     80 non-null     object
 3   Grade    82 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.8+ KB

In [14]:
# Take a look at the unique values (including NaN) in the Year column
df.Year.value_counts(dropna=False)

Year
Freshman     35
Sophomore    24
Junior       20
NaN           6
Senior        1
Name: count, dtype: int64

In [15]:
# All cells that have a NaN value
df.isna()

    Student  Class   Year  Grade
0     False  False  False  False
1     False  False  False  False
2     False  False  False  False
3     False  False  False  False
4     False  False  False  False
..      ...    ...    ...    ...
81     True   True   True   True
82    False   True   True   True
83     True  False  False  False
84    False  False  False   True
85    False   True   True  False

[86 rows x 4 columns]

In [16]:
# Number of missing values in each column
df.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [17]:
# VIEW THE ROWS WITH MISSING VALUES
df[df.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

### b. Handle missing data

In [18]:
# Drop rows that don't have a student or class name
df[df.isna().any(axis=1)].dropna(subset=['Student', 'Class'])

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

In [19]:
# Apply to entire DataFrame
df.dropna(subset=['Student', 'Class'], inplace=True)
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
77    Aaron               EDA    Junior   85.0
78  Charles               EDA    Junior   93.0
79   Connor               EDA    Junior   91.0
80    Riley               EDA    Junior   87.0
84    Gavin               EDA    Senior    NaN

[82 rows x 4 columns]

In [20]:
# Check the rows with missing grades
df[df.Grade.isna()]

   Student                      Class    Year  Grade
62  Landon  Exploratory Data Analysis  Junior    NaN
84   Gavin                        EDA  Senior    NaN

In [21]:
# Impute the NaN grades
# df.Grade.fillna(df.Grade.mean(), inplace=True)
df.fillna({'Grade': df.Grade.mean()}, inplace=True)
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

In [22]:
# Check the rows with NaNs
df[df.isna().any(axis=1)]

   Student             Class Year  Grade
7    Jacob  Freshman Seminar  NaN   88.0
8  William  Freshman Seminar  NaN   89.0
9    Ethan  Freshman Seminar  NaN   86.0

In [23]:
# Look at all Freshman Seminar students
df[df.Class == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [24]:
# UPDATE A SPECIFIC VALUE
df.loc[7, 'Year'] = 'Freshman'

In [25]:
df.loc[7]

Student               Jacob
Class      Freshman Seminar
Year               Freshman
Grade                  88.0
Name: 7, dtype: object

In [26]:
# UPDATE MULTIPLE VALUES USING np.where
df.Year = np.where(df.Year.isna(), 'Freshman', df.Year)
df

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

In [27]:
# CHECK IF WE STILL HAVE ROWS WITH NaNs
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Student, Class, Year, Grade]
Index: []

## 3. Inconsistent Text and Typos

### a. Find inconsistent text and typos

In [28]:
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [29]:
# Find inconsistencies in categorical columns
df.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [30]:
# Look at Exploratory Data Analysis students vs EDA students
df[df.Class.isin(['Exploratory Data Analysis', 'EDA'])]

      Student                      Class       Year   Grade
58     Evelyn  Exploratory Data Analysis  Sophomore   89.00
59       Jack  Exploratory Data Analysis  Sophomore   84.00
60       Ella  Exploratory Data Analysis  Sophomore  200.00
61      Chloe  Exploratory Data Analysis  Sophomore   87.00
62     Landon  Exploratory Data Analysis     Junior   85.55
63  Christian  Exploratory Data Analysis     Junior   77.00
64     Jordan  Exploratory Data Analysis     Junior   83.00
65   Jonathan  Exploratory Data Analysis     Junior   82.00
66       Levi  Exploratory Data Analysis     Junior   91.00
67   Victoria  Exploratory Data Analysis     Junior   90.00
68     Aubrey  Exploratory Data Analysis     Junior   83.00
69      Jaxon  Exploratory Data Analysis     Junior   64.00
70     Julian                        EDA     Junior   95.00
71      Grace                        EDA     Junior   77.00
72     Isaiah                        EDA     Junior   88.00
73    Cameron                        EDA     Junior   72.00
74        Eli                        EDA     Junior   92.00
75      Angel                        EDA     Junior   79.00
76       Zoey                        EDA     Junior   91.00
77      Aaron                        EDA     Junior   85.00
78    Charles                        EDA     Junior   93.00
79     Connor                        EDA     Junior   91.00
80      Riley                        EDA     Junior   87.00
84      Gavin                        EDA     Senior   85.55

In [31]:
# Look at Intro to Python students vs Python students
df[df.Class.isin(['Intro to Python', 'Python'])]

      Student            Class      Year  Grade
12  Alexander  Intro to Python  Freshman   85.0
13      Logan  Intro to Python  Freshman   85.0
14      James  Intro to Python  Freshman   82.0
15     Daniel  Intro to Python  Freshman   85.0
16     Elijah  Intro to Python  Freshman   85.0
17   Benjamin  Intro to Python  Freshman   81.0
18        Mia  Intro to Python  Freshman   80.0
19        Mia           Python  Freshman   80.0
20     Jayden  Intro to Python  Freshman   82.0
21      Aiden  Intro to Python  Freshman   86.0
22    Matthew  Intro to Python  Freshman   87.0
23      Emily  Intro to Python  Freshman   78.0
24    Jackson  Intro to Python  Freshman   88.0
25      Lucas  Intro to Python  Freshman   77.0
26      David  Intro to Python  Freshman   74.0
27     Joseph  Intro to Python  Freshman   93.0
28    Abigail  Intro to Python  Freshman   89.0
29      Avery  Intro to Python  Freshman   79.0
30    Anthony  Intro to Python  Freshman   84.0
31      Dylan  Intro to Python  Freshman   84.0
32     Andrew  Intro to Python  Freshman   94.0
33     Carter  Intro to Python  Freshman   95.0
34     Samuel  Intro to Python  Freshman   83.0
35    Gabriel  Intro to Python  Freshman   82.0
36     Joshua  Intro to Python  Freshman   71.0
37       John  Intro to Python  Freshman   50.0

In [32]:
# Find inconsistencies in categorical columns
df.Year.value_counts()

Year
Freshman     38
Sophomore    24
Junior       19
Senior        1
Name: count, dtype: int64

In [34]:
# Find inconsistencies in numerical columns
df.Grade.describe()

count     82.000000
mean      85.550000
std       15.443965
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      200.000000
Name: Grade, dtype: float64

In [35]:
df[df.Grade > 100]

   Student                      Class       Year  Grade
60    Ella  Exploratory Data Analysis  Sophomore  200.0

### b. Handle inconsistent text and typos

In [36]:
df.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [37]:
# Check the unique class values
df.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [38]:
# Replace EDA with Exploratory Data Analysis
df.Class = np.where(df.Class == 'EDA', 'Exploratory Data Analysis', df.Class)
df.Class.value_counts()

Class
Intro to Python              25
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Python                        1
Name: count, dtype: int64

In [39]:
# Replace Python with Intro to Python
df.Class = np.where(df.Class == 'Python', 'Intro to Python', df.Class)
df.Class.value_counts()

Class
Intro to Python              26
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Name: count, dtype: int64

In [40]:
# Find grades over 100
df[df.Grade > 100]

   Student                      Class       Year  Grade
60    Ella  Exploratory Data Analysis  Sophomore  200.0

In [41]:
# Replace the 200 value with 100
df.Grade = np.where(df.Grade > 100, 100, df.Grade)
df.Grade.describe()

count     82.000000
mean      84.330488
std        8.824663
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      100.000000
Name: Grade, dtype: float64